name: rh-rnalysis
channels:
   - nodefaults
   - conda-forge
   - bioconda
   - defaults
dependencies:
  - python=3.8
  - bioconda::samtools
  - bioconda::subread
  - bioconda::fastqc
  - bioconda::multiqc
  - bioconda::trim-galore
  - bioconda::qualimap
  - bioconda::hisat2
  - bioconda::gffread
  - bioconda::bedtools
  - conda-forge::pandas  
