name: rh-rnalysis
channels:
   - nodefaults
   - conda-forge
   - bioconda
   - defaults
dependencies:
  - python=3.7
  - bioconda::samtools
  - bioconda::subread
  - bioconda::fastqc
  - bioconda::multiqc
  - bioconda::bowtie2 #
  - bioconda::kallisto #
  - bioconda::bioconductor-deseq2 #
  - bioconda::trim-galore
  - bioconda::qualimap
  - bioconda::rsem #
  - bioconda::hisat2
  - bioconda::gffread
  - conda-forge::pandas
